version: "3.3"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.3
    volumes:
      - cardano-node-db:/data/db
      - cardano-node-ipc:/ipc
      - ./config/preview:/var/cardano/config
    restart: on-failure
    command:
      - "run"
      - "--config /var/cardano/config/config.json"
      - "--topology /var/cardano/config/topology.json"
      - "--database-path /data/db"
      - "--socket-path /ipc/node.socket"
    healthcheck:
      # Ping the EKG port to see if it responds.
      # Assuming if EKG isn't up then the rest of cardano-node isn't either.
      test: ["CMD-SHELL", "curl -f 127.0.0.1:12788 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  spectrum-cardano-backend:
    image: spectrumlabs/spectrum-cardano-backend:0.0.1
    volumes:
      - spectrum-backend-volume:/data
      - ./config/preview:/var/cardano/config
      - /home/bromel/projects/cardano-dex-backend/wallet1TS.json:/etc/wallet1TS.json
      - ./scripts:/scripts
      - ./config/spectrum/dcSpectrumConfig.dhall:/etc/appConfig.dhall
      - cardano-node-ipc:/ipc
    restart: on-failure
    depends_on:
      - cardano-node
    command:
      - "/etc/appConfig.dhall"
volumes:
  cardano-node-db:
  cardano-node-ipc:
  spectrum-backend-volume: